# backend/apps/reviews/models.py

from django.conf import settings
from django.db import models


class Review(models.Model):
    """
    Represents a single code review request and its AI-generated response.

    Lifecycle:
        1. User submits code + optional question → status: PENDING
        2. Celery picks up the task → status: PROCESSING
        3. LLM responds → status: COMPLETED (or FAILED on error)

    The AI response fields (issues, suggestions, quality_score) are
    null until the review is completed.
    """

    # ── Language Choices ──────────────────────────────────────────
    class Language(models.TextChoices):
        """
        Using TextChoices (Django 3.0+) instead of a plain list of tuples.
        Gives you: Review.Language.PYTHON, Review.Language.choices, etc.
        Clean, readable, and IDE-friendly.
        """
        PYTHON = 'python', 'Python'
        JAVASCRIPT = 'javascript', 'JavaScript'
        TYPESCRIPT = 'typescript', 'TypeScript'
        JAVA = 'java', 'Java'
        CPP = 'cpp', 'C++'
        C = 'c', 'C'
        GO = 'go', 'Go'
        RUST = 'rust', 'Rust'
        PHP = 'php', 'PHP'
        RUBY = 'ruby', 'Ruby'
        SWIFT = 'swift', 'Swift'
        KOTLIN = 'kotlin', 'Kotlin'
        SQL = 'sql', 'SQL'
        BASH = 'bash', 'Bash/Shell'
        OTHER = 'other', 'Other'

    # ── Status Choices ────────────────────────────────────────────
    class Status(models.TextChoices):
        PENDING = 'pending', 'Pending'
        PROCESSING = 'processing', 'Processing'
        COMPLETED = 'completed', 'Completed'
        FAILED = 'failed', 'Failed'

    # ── Core Fields ───────────────────────────────────────────────
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='reviews'      # Access via: user.reviews.all()
    )
    # Why settings.AUTH_USER_MODEL and not importing User directly?
    # Avoids circular imports. Always the correct practice with custom user models.

    language = models.CharField(
        max_length=20,
        choices=Language.choices,
    )

    code_snippet = models.TextField()

    question = models.TextField(
        blank=True,
        default='',
        help_text="Optional context for the reviewer. Defaults to 'Review this code' if empty."
    )

    # ── Status ────────────────────────────────────────────────────
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.PENDING,
        db_index=True   # We'll query by status often — index it
    )

    # ── AI Response (populated after LLM completes) ───────────────
    issues = models.JSONField(
        default=list,       # Default to empty list, not null
        blank=True
    )
    suggestions = models.JSONField(
        default=list,
        blank=True
    )
    quality_score = models.PositiveSmallIntegerField(
        null=True,
        blank=True,
        help_text="Score from 0 to 100 generated by the LLM."
    )
    raw_response = models.TextField(
        blank=True,
        default='',
        help_text="Full raw LLM response. Stored for debugging purposes."
    )
    summary = models.TextField(
    blank=True,
    default='',
    help_text="Brief overall assessment generated by the LLM."
    )

    # ── Timestamps ────────────────────────────────────────────────
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'reviews'
        ordering = ['-created_at']

    def __str__(self):
        return f"Review #{self.id} by {self.user.username} [{self.language}]"

    @property
    def prompt(self):
        """
        Returns the actual question sent to the LLM.
        If user left question empty, returns the default prompt.
        This logic lives here so the service layer stays clean.
        """
        return self.question.strip() if self.question.strip() else "Review this code"