# Generated by Django 5.0.4 on 2026-03-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='Brief overall assessment generated by the LLM.'),
        ),
    ]
