# Generated by Django 5.0.4 on 2026-09-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='question_answer',
            field=models.TextField(blank=True, default='', help_text="AI's direct answer to the user's question."),
        ),
    ]
